import type { Product, Category, DiscountCode } from './types';

export const mockCategories: Category[] = [
  { id: 'cat-women', slug: 'women', name: 'زنانه', english_name: 'Women', parent_id: null, description: 'سبک روزمره با ظاهری مینیمال و راحت', image: 'categories/women.svg', sort_order: 1 },
  { id: 'cat-men', slug: 'men', name: 'مردانه', english_name: 'Men', parent_id: null, description: 'پوشاک مدرن برای مردی با اعتماد', image: 'categories/men.svg', sort_order: 2 },
  { id: 'cat-shoes', slug: 'shoes', name: 'کفش', english_name: 'Shoes', parent_id: null, description: 'کفش‌هایی که هر قدم را همراهی می‌کنند', image: 'categories/shoes.svg', sort_order: 3 },
  { id: 'cat-women-clothing', slug: 'women-clothing', name: 'پوشاک', english_name: 'Clothing', parent_id: 'cat-women', description: null, image: null, sort_order: 1 },
  { id: 'cat-women-tops', slug: 'women-tops', name: 'تاپ و بلوز', english_name: 'Tops', parent_id: 'cat-women', description: null, image: null, sort_order: 2 },
  { id: 'cat-women-pants', slug: 'women-pants', name: 'شلوار', english_name: 'Pants', parent_id: 'cat-women', description: null, image: null, sort_order: 3 },
  { id: 'cat-women-dresses', slug: 'women-dresses', name: 'مانتو و dresses', english_name: 'Dresses', parent_id: 'cat-women', description: null, image: null, sort_order: 4 },
  { id: 'cat-women-accessories', slug: 'women-accessories', name: 'اکسسوری', english_name: 'Accessories', parent_id: 'cat-women', description: null, image: null, sort_order: 5 },
  { id: 'cat-men-shirts', slug: 'men-shirts', name: 'پیراهن', english_name: 'Shirts', parent_id: 'cat-men', description: null, image: null, sort_order: 1 },
  { id: 'cat-men-tshirts', slug: 'men-tshirts', name: 'تیشرت', english_name: 'T-Shirts', parent_id: 'cat-men', description: null, image: null, sort_order: 2 },
  { id: 'cat-men-pants', slug: 'men-pants', name: 'شلوار', english_name: 'Pants', parent_id: 'cat-men', description: null, image: null, sort_order: 3 },
  { id: 'cat-men-jackets', slug: 'men-jackets', name: 'ژکت', english_name: 'Jackets', parent_id: 'cat-men', description: null, image: null, sort_order: 4 },
  { id: 'cat-men-hoodies', slug: 'men-hoodies', name: 'هودی و سویشرت', english_name: 'Hoodies', parent_id: 'cat-men', description: null, image: null, sort_order: 5 },
];

const sg = (chest: Record<string, string>, length: Record<string, string>) => ({ chest, length });

export const mockProducts: Product[] = [
  // Women
  { id: 'p-w-blazer', slug: 'w-blazer', name: 'Cream Minimal Blazer', name_fa: 'بلیزر کرم مینیمال', category_id: 'cat-women-clothing', category: 'women', subcategory: 'women-clothing', price: 1850000, old_price: null, images: ['products/w-blazer.svg'], description: 'بلیزر کرم رنگ با برش تمیز و پارچه نرم. مناسب استایل روزمره و رسمی.', material: 'پلی‌استر ۶۰٪ / ویسکوز ۴۰٪', colors: ['#e7d3b8', '#141414', '#818181'], sizes: ['S', 'M', 'L', 'XL'], size_guide: sg({ S: '96', M: '100', L: '104', XL: '108' }, { S: '62', M: '64', L: '66', XL: '68' }), related_ids: ['p-w-dress', 'p-w-pants', 'p-w-shirt'], tag: 'جدید', stock: 24, is_active: true, is_bestseller: false, is_new: true, sort_order: 1 },
  { id: 'p-w-dress', slug: 'w-dress', name: 'Minimal Mantou Dress', name_fa: 'مانتو مینیمال', category_id: 'cat-women-dresses', category: 'women', subcategory: 'women-dresses', price: 2480000, old_price: null, images: ['products/w-dress.svg'], description: 'مانتو مینیمال با خطوط ساده و پارچه مرغوب. طراحی شیک برای روزهای کاری.', material: 'کجر ۱۰۰٪', colors: ['#2a2a2a', '#C8A97E'], sizes: ['S', 'M', 'L'], size_guide: sg({ S: '94', M: '98', L: '102' }, { S: '100', M: '102', L: '104' }), related_ids: ['p-w-blazer', 'p-w-pants', 'p-w-scarf'], tag: 'جدید', stock: 18, is_active: true, is_bestseller: false, is_new: true, sort_order: 2 },
  { id: 'p-w-shirt', slug: 'w-shirt', name: 'Silk Blouse', name_fa: 'شومیز ابریشمی', category_id: 'cat-women-tops', category: 'women', subcategory: 'women-tops', price: 1620000, old_price: 2100000, images: ['products/w-shirt.svg'], description: 'شومیز لطیف با افتادگی زیبا. مناسب ترکیب با شلوار کلاسیک.', material: 'ابریشم طبیعی', colors: ['#f0e8d8', '#1f1f1f', '#b8915f'], sizes: ['S', 'M', 'L', 'XL'], size_guide: sg({ S: '92', M: '96', L: '100', XL: '104' }, { S: '60', M: '62', L: '64', XL: '66' }), related_ids: [], tag: 'پرفروش', stock: 30, is_active: true, is_bestseller: true, is_new: false, sort_order: 3 },
  { id: 'p-w-pants', slug: 'w-pants', name: 'Cotton Trousers', name_fa: 'شلوار کتان', category_id: 'cat-women-pants', category: 'women', subcategory: 'women-pants', price: 1340000, old_price: null, images: ['products/w-pants.svg'], description: 'شلوار کتان با راحتی بالا و دوخت پایدار. مناسب استایل روزمره.', material: 'کتان ۱۰۰٪', colors: ['#3a3a3a', '#C8A97E'], sizes: ['XS', 'S', 'M', 'L'], size_guide: { waist: { XS: '64', S: '68', M: '72', L: '76' }, length: { XS: '96', S: '98', M: '100', L: '102' } }, related_ids: [], tag: null, stock: 22, is_active: true, is_bestseller: false, is_new: false, sort_order: 4 },
  { id: 'p-w-coat', slug: 'w-coat', name: 'Charcoal Coat', name_fa: 'پالتو چارکول', category_id: 'cat-women-clothing', category: 'women', subcategory: 'women-clothing', price: 3950000, old_price: 4500000, images: ['products/w-coat.svg'], description: 'پالتو گرم با ظاهر کلاسیک. مناسب فصل سرد و استایل رسمی.', material: 'پشم ۷۰٪ / کجر ۳۰٪', colors: ['#1f1f1f', '#C8A97E'], sizes: ['S', 'M', 'L', 'XL'], size_guide: sg({ S: '100', M: '104', L: '108', XL: '112' }, { S: '98', M: '100', L: '102', XL: '104' }), related_ids: [], tag: 'پرفروش', stock: 12, is_active: true, is_bestseller: true, is_new: false, sort_order: 5 },
  { id: 'p-w-scarf', slug: 'w-scarf', name: 'Crepe Scarf', name_fa: 'شال کرپ', category_id: 'cat-women-accessories', category: 'women', subcategory: 'women-accessories', price: 680000, old_price: null, images: ['products/w-scarf.svg'], description: 'شال کرپ نرم با رنگ‌های خنثی. اکسسوری مینیمال برای تکمیل استایل.', material: 'کرپ پلی‌استر', colors: ['#b8915f', '#f0e8d8'], sizes: ['ONE'], size_guide: {}, related_ids: [], tag: null, stock: 40, is_active: true, is_bestseller: false, is_new: true, sort_order: 6 },
  { id: 'p-w-set', slug: 'w-set', name: 'Mantou Pants Set', name_fa: 'مانتو شلوار ست', category_id: 'cat-women-clothing', category: 'women', subcategory: 'women-clothing', price: 2480000, old_price: null, images: ['products/w-set.svg'], description: 'ست مینیمال با خطوط ساده و پارچه مرغوب. آماده برای استایل روزمره.', material: 'ویسکوز ۱۰۰٪', colors: ['#333333', '#C8A97E'], sizes: ['S', 'M', 'L'], size_guide: sg({ S: '96', M: '100', L: '104' }, { S: '100', M: '102', L: '104' }), related_ids: [], tag: 'جدید', stock: 16, is_active: true, is_bestseller: false, is_new: true, sort_order: 7 },
  { id: 'p-w-top', slug: 'w-top', name: 'Cotton Top', name_fa: 'تاپ نخی', category_id: 'cat-women-tops', category: 'women', subcategory: 'women-tops', price: 720000, old_price: null, images: ['products/w-top.svg'], description: 'تاپ نخی سبک و راحت برای روزهای گرم.', material: 'نخ ۱۰۰٪', colors: ['#e7d3b8', '#1f1f1f'], sizes: ['XS', 'S', 'M', 'L'], size_guide: sg({ XS: '86', S: '90', M: '94', L: '98' }, { XS: '54', S: '56', M: '58', L: '60' }), related_ids: [], tag: null, stock: 35, is_active: true, is_bestseller: false, is_new: false, sort_order: 8 },
  // Men
  { id: 'p-m-shirt', slug: 'm-shirt', name: 'Long Sleeve Shirt', name_fa: 'پیراهن آستین‌بلند', category_id: 'cat-men-shirts', category: 'men', subcategory: 'men-shirts', price: 980000, old_price: null, images: ['products/m-shirt.svg'], description: 'پیراهن روزمره با پارچه تنفس‌پذیر. مناسب استایل کژوال و رسمی.', material: 'کتن ۱۰۰٪', colors: ['#f3e9da', '#333333'], sizes: ['S', 'M', 'L', 'XL', 'XXL'], size_guide: sg({ S: '100', M: '104', L: '108', XL: '112', XXL: '116' }, { S: '72', M: '74', L: '76', XL: '78', XXL: '80' }), related_ids: ['p-m-pants', 'p-m-tshirt', 'p-m-hoodie'], tag: 'پرفروش', stock: 28, is_active: true, is_bestseller: true, is_new: false, sort_order: 1 },
  { id: 'p-m-tshirt', slug: 'm-tshirt', name: 'Brazilian T-Shirt', name_fa: 'تیشرت برزیلی', category_id: 'cat-men-tshirts', category: 'men', subcategory: 'men-tshirts', price: 540000, old_price: null, images: ['products/m-tshirt.svg'], description: 'تیشرت برزیلی نرم با دوخت پایدار. پایه استایل روزمره.', material: 'نخ پنبه ۱۰۰٪', colors: ['#1f1f1f', '#C8A97E', '#666666'], sizes: ['S', 'M', 'L', 'XL', 'XXL'], size_guide: sg({ S: '96', M: '100', L: '104', XL: '108', XXL: '112' }, { S: '68', M: '70', L: '72', XL: '74', XXL: '76' }), related_ids: [], tag: 'جدید', stock: 50, is_active: true, is_bestseller: false, is_new: true, sort_order: 2 },
  { id: 'p-m-pants', slug: 'm-pants', name: 'Denim Jeans', name_fa: 'شلوار جین', category_id: 'cat-men-pants', category: 'men', subcategory: 'men-pants', price: 1280000, old_price: null, images: ['products/m-pants.svg'], description: 'شلوار جین با برش راحت و رنگ پایدار. استایل کژوال مدرن.', material: 'دنیم ۹۸٪ / الاستن ۲٪', colors: ['#2a3a4a', '#1f1f1f'], sizes: ['30', '32', '34', '36', '38'], size_guide: { waist: { '30': '76', '32': '81', '34': '86', '36': '91', '38': '96' }, length: { '30': '98', '32': '100', '34': '102', '36': '104', '38': '106' } }, related_ids: [], tag: null, stock: 26, is_active: true, is_bestseller: false, is_new: false, sort_order: 3 },
  { id: 'p-m-jacket', slug: 'm-jacket', name: 'Leather Jacket', name_fa: 'ژکت چرمی', category_id: 'cat-men-jackets', category: 'men', subcategory: 'men-jackets', price: 3120000, old_price: 3600000, images: ['products/m-jacket.svg'], description: 'ژکت چرمی با دوام بالا و ظاهر کلاسیک. قطعه‌ای ماندگار در کمد.', material: 'چرم طبیعی', colors: ['#1a1a1a', '#8a6a3e'], sizes: ['M', 'L', 'XL', 'XXL'], size_guide: sg({ M: '108', L: '112', XL: '116', XXL: '120' }, { M: '66', L: '68', XL: '70', XXL: '72' }), related_ids: [], tag: 'پرفروش', stock: 10, is_active: true, is_bestseller: true, is_new: false, sort_order: 4 },
  { id: 'p-m-hoodie', slug: 'm-hoodie', name: 'Charcoal Hoodie', name_fa: 'هودی چارکول', category_id: 'cat-men-hoodies', category: 'men', subcategory: 'men-hoodies', price: 1290000, old_price: null, images: ['products/m-hoodie.svg'], description: 'هودی نرم و گرم با دوخت پایدار. راحتی و استایل در کنار هم.', material: 'فلیس پنبه', colors: ['#2a2a2a', '#C8A97E', '#666666'], sizes: ['S', 'M', 'L', 'XL', 'XXL'], size_guide: sg({ S: '104', M: '108', L: '112', XL: '116', XXL: '120' }, { S: '66', M: '68', L: '70', XL: '72', XXL: '74' }), related_ids: ['p-m-pants', 'p-m-jacket', 'p-s-white'], tag: 'جدید', stock: 32, is_active: true, is_bestseller: false, is_new: true, sort_order: 5 },
  { id: 'p-m-sweater', slug: 'm-sweater', name: 'Soft Sweater', name_fa: 'سویشرت نرم', category_id: 'cat-men-hoodies', category: 'men', subcategory: 'men-hoodies', price: 1150000, old_price: null, images: ['products/m-sweater.svg'], description: 'سویشرت نرم با بافت لطیف. مناسب لایه‌گذاری در فصل سرد.', material: 'پشم مرینوس', colors: ['#4a4a4a', '#C8A97E'], sizes: ['M', 'L', 'XL'], size_guide: sg({ M: '108', L: '112', XL: '116' }, { M: '68', L: '70', XL: '72' }), related_ids: [], tag: null, stock: 20, is_active: true, is_bestseller: false, is_new: false, sort_order: 6 },
  // Shoes
  { id: 'p-s-white', slug: 's-white', name: 'Classic White Sneaker', name_fa: 'اسنیکرز سفید کلاسیک', category_id: 'cat-shoes', category: 'shoes', subcategory: null, price: 2150000, old_price: null, images: ['products/s-white.svg'], description: 'کفش روزمره با کفی راحت و طراحی تمیز. مناسب استایل مینیمال.', material: 'چرم مصنوعی / کفی پلاستیک', colors: ['#f0ece4', '#1f1f1f'], sizes: ['38', '39', '40', '41', '42', '43', '44'], size_guide: { eu: { '38': '38', '39': '39', '40': '40', '41': '41', '42': '42', '43': '43', '44': '44' } }, related_ids: [], tag: 'جدید', stock: 24, is_active: true, is_bestseller: false, is_new: true, sort_order: 1 },
  { id: 'p-s-black', slug: 's-black', name: 'Black Leather Shoes', name_fa: 'کفش چرم مشکی', category_id: 'cat-shoes', category: 'shoes', subcategory: null, price: 2390000, old_price: 2900000, images: ['products/s-black.svg'], description: 'کفش چرم با دوام و ظاهر کلاسیک. مناسب استایل رسمی و روزمره.', material: 'چرم طبیعی', colors: ['#141414', '#818181'], sizes: ['39', '40', '41', '42', '43', '44'], size_guide: { eu: { '39': '39', '40': '40', '41': '41', '42': '42', '43': '43', '44': '44' } }, related_ids: ['p-s-white', 'p-s-boot'], tag: 'پرفروش', stock: 18, is_active: true, is_bestseller: true, is_new: false, sort_order: 2 },
  { id: 'p-s-boot', slug: 's-boot', name: 'Winter Boot', name_fa: 'بوت زمستانی', category_id: 'cat-shoes', category: 'shoes', subcategory: null, price: 2890000, old_price: null, images: ['products/s-boot.svg'], description: 'بوت گرم با ضدآب و کفی مقاوم. مناسب فصل سرما.', material: 'چرم مصنوعی / پشم داخلی', colors: ['#3a2a1a', '#C8A97E'], sizes: ['40', '41', '42', '43', '44'], size_guide: { eu: { '40': '40', '41': '41', '42': '42', '43': '43', '44': '44' } }, related_ids: [], tag: null, stock: 14, is_active: true, is_bestseller: false, is_new: false, sort_order: 3 },
  { id: 'p-s-sandal', slug: 's-sandal', name: 'Summer Sandal', name_fa: 'صندل تابستانی', category_id: 'cat-shoes', category: 'shoes', subcategory: null, price: 890000, old_price: null, images: ['products/s-sandal.svg'], description: 'صندل سبک و راحت برای روزهای گرم. طراحی مینیمال.', material: 'چرم مصنوعی', colors: ['#C8A97E', '#1f1f1f'], sizes: ['38', '39', '40', '41', '42'], size_guide: { eu: { '38': '38', '39': '39', '40': '40', '41': '41', '42': '42' } }, related_ids: [], tag: null, stock: 30, is_active: true, is_bestseller: false, is_new: false, sort_order: 4 },
];

export const mockDiscounts: DiscountCode[] = [
  { id: 'd1', code: 'VEXR10', type: 'percent', value: 10, min_spend: 0, active: true, expires_at: null, usage_count: 0, usage_limit: 1000 },
  { id: 'd2', code: 'WELCOME15', type: 'percent', value: 15, min_spend: 1500000, active: true, expires_at: null, usage_count: 0, usage_limit: 500 },
  { id: 'd3', code: 'OFF200', type: 'amount', value: 200000, min_spend: 1000000, active: true, expires_at: null, usage_count: 0, usage_limit: 200 },
];
